### ISSUE TITLE
General Bug Reports

### ISSUE THREAD

**Issue by Zeeex** [Zeeex/Simple-Modern-Dark-Microsoft#5]
**Post any bugs you find (Style not working correctly or not compatible)**

**Comment by CollinChaffin** [comment]
This MS site partially themed making only the text white (even with the new force white off) but nothing else themed which obviously forces having to disable script for this subsite for now (or as I've done exclude it in GM).....just wanted you to be aware since I believe this subsite is relatively new.

https://techcommunity.microsoft.com

**Comment by Zeeex** [comment]
Thanks for the reports Collin. Fixed in v2.10.

**Comment by CollinChaffin** [comment]
@Zeeex  confirmed looks AWESOME as usual on this subsite!  You rock!  +1

**Comment by CollinChaffin** [comment]
LOL okay so it's me again :)

I swear don't know what the heck is with MS lately because the exact other side of this same darn gallery is what you just fixed last......yet look at the elements now on this:

https://gallery.technet.microsoft.com/office/Check-for-unsupported-6676929a

**Comment by Zeeex** [comment]
Fixed in 2.12!

**Comment by CollinChaffin** [comment]
....and as usual, looks perfect! :_onion_head_cheer2:

**Comment by CollinChaffin** [comment]
LOL, OMG, after this you're going to start hating MS......didn't you just have to already fix this with these code boxes on this exact blog subsite?

https://blogs.msdn.microsoft.com/codedebate/2007/12/18/ntfs-sparse-files-with-c/

**Comment by Zeeex** [comment]
Fixed in 2.3

**Comment by CollinChaffin** [comment]
Those last two updates have been great!  Here is one more weird element, especially since all the other elements in this section seem okay so maybe it's just a rename or something:

https://blogs.msdn.microsoft.com/powershell/2017/08/23/dsc-resource-kit-release-august-2017/

(Note the table does has text it's just white)

**Comment by CollinChaffin** [comment]
Found a couple more looks like MS changed the blogs.office blocks too (maybe?):

https://blogs.office.com/en-us/2011/12/08/organize-your-recipes-with-a-onenote-cookbook/

**Comment by Zeeex** [comment]
Fixed in 2.4
